import { createFileRoute, Link } from "@tanstack/react-router";
import { CheckCircle2, ExternalLink, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { parishes } from "@/data/parishes";
export const Route=createFileRoute("/find-a-parish/$parishId")({head:({params})=>{const p=parishes.find(x=>x.id===params.parishId);const title=`${p?.name??"Sample parish"} — Anglican Path`;const description=`Fictitious sample parish detail for ${p?.city??"Anytown"}.`;return{meta:[{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]};},component:ParishDetail});
function ParishDetail(){const{parishId}=Route.useParams();const p=parishes.find(x=>x.id===parishId)??parishes[0];if(!p)return <main className="mx-auto max-w-3xl px-5 py-24"><h1 className="font-display text-5xl">Parish not found</h1></main>;return <main><div className="mx-auto max-w-5xl px-5 py-12 sm:px-8"><Link to="/find-a-parish" className="text-sm text-primary">← Back to parish finder</Link><div className="mt-8 border-y-2 border-primary py-10"><span className="inline-block bg-primary/10 px-2 py-1 text-xs font-bold uppercase text-primary">Sample Data · Fictitious Parish</span><div className="mt-5 flex flex-wrap items-start justify-between gap-5"><div><h1 className="font-display text-4xl font-semibold sm:text-6xl">{p.name}</h1><p className="mt-4 flex items-center gap-2 text-muted-foreground"><MapPin className="size-4"/>{p.address}</p></div>{p.verified&&<span className="flex items-center gap-2 text-sm font-semibold text-primary"><CheckCircle2 className="size-5"/>Verified by parish</span>}</div></div><div className="grid gap-12 py-12 md:grid-cols-[1fr_18rem]"><div><h2 className="font-display text-3xl font-semibold">Service schedule</h2><ul className="mt-5 divide-y divide-border border-y border-border">{p.services.map(s=><li className="py-4" key={s}>{s} · {p.serviceType}</li>)}</ul><h2 className="mt-12 font-display text-3xl font-semibold">About this parish</h2><p className="mt-4 leading-8 text-muted-foreground">[Fictitious parish description placeholder. Draft to be written.]</p></div><aside className="border-t border-border pt-5"><dl className="space-y-4 text-sm"><div><dt className="text-muted-foreground">Jurisdiction</dt><dd className="font-semibold">{p.jurisdiction}</dd></div><div><dt className="text-muted-foreground">Prayer Book</dt><dd className="font-semibold">{p.book}</dd></div><div><dt className="text-muted-foreground">Churchmanship</dt><dd className="font-semibold">{p.churchmanship}</dd></div></dl><Button variant="outline" className="mt-7 w-full" asChild><a href={p.website}>Parish website <ExternalLink/></a></Button><UpdateDialog/></aside></div></div></main>}
function UpdateDialog(){return <Dialog><DialogTrigger asChild><Button variant="ghost" className="mt-2 h-11 w-full">Suggest an update</Button></DialogTrigger><DialogContent className="max-h-[90dvh] w-[calc(100%-2rem)] overflow-y-auto"><DialogHeader><DialogTitle className="font-display text-2xl">Suggest an update</DialogTitle><DialogDescription>This prototype form does not submit information.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e=>e.preventDefault()}><Input className="h-11" placeholder="Your name" aria-label="Your name"/><Input className="h-11" type="email" placeholder="Email address" aria-label="Email address"/><textarea className="min-h-32 w-full rounded-md border border-input bg-background p-3 text-sm" placeholder="What should be updated?" aria-label="Suggested update"/><Button className="h-11" type="submit">Send suggestion</Button></form></DialogContent></Dialog>}
