import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpenText, Church, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ArticleCard } from "@/components/site/article-card";
import { Ornament } from "@/components/site/site-shell";
import { articles, paths } from "@/data/content";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "Anglican Path — Discover, Find, Pray" }, { name: "description", content: "Discover the Anglican faith, find a traditional Anglican parish, and pray the Daily Office." }, { property: "og:title", content: "Anglican Path — Discover, Find, Pray" }, { property: "og:description", content: "Discover the Anglican faith, find a traditional Anglican parish, and pray the Daily Office." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Index });
const entries = [{ title: "Learn", body: "Explore clear, carefully reviewed guides to Anglican belief and practice.", to: "/learn" as const, icon: BookOpenText }, { title: "Find a Parish", body: "Search our prototype directory of traditional Anglican churches.", to: "/find-a-parish" as const, icon: Search }, { title: "Pray Today", body: "Follow Morning or Evening Prayer in a focused reading view.", to: "/office" as const, icon: Church }];
function Index() { return <main>
  <section className="relative overflow-hidden border-b border-border"><div className="mx-auto max-w-7xl px-5 py-20 text-center sm:px-8 sm:py-28"><div className="mx-auto text-2xl text-primary" aria-hidden="true">†</div><h1 className="mx-auto mt-7 max-w-5xl font-display text-5xl font-semibold leading-[1.05] sm:text-7xl">Find an Anglican church. Discover the Anglican faith. Pray the Daily Office.</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">A quiet, trustworthy place to begin—or continue—your path in the Anglican tradition.</p></div></section>
  <section className="mx-auto max-w-7xl px-5 py-14 sm:px-8 sm:py-20"><div className="grid gap-px overflow-hidden border border-border bg-border md:grid-cols-3">{entries.map(({title,body,to,icon:Icon}) => <Link key={title} to={to} className="group bg-background p-7 transition-colors hover:bg-secondary/35 sm:p-9"><Icon className="size-6 text-primary"/><h2 className="mt-7 font-display text-3xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{body}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-primary">Begin here <ArrowRight className="size-4"/></span></Link>)}</div></section>
  <section className="border-y border-border bg-secondary/25"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><div className="max-w-2xl"><p className="text-xs font-bold uppercase text-primary">Guided reading</p><h2 className="mt-3 font-display text-4xl font-semibold sm:text-5xl">Start your path</h2><p className="mt-4 leading-7 text-muted-foreground">Choose the background that best describes you. Each path is a short sequence of readings.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{paths.map((path,i) => <Link key={path.id} to="/paths/$pathId" params={{pathId:path.id}} className="border-t-2 border-primary bg-background p-5 shadow-sm transition-transform hover:-translate-y-1"><span className="text-xs font-bold text-primary">0{i+1}</span><h3 className="mt-10 font-display text-2xl font-semibold leading-tight">{path.title}</h3><ArrowRight className="mt-5 size-4 text-primary"/></Link>)}</div></div></section>
  <section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 sm:py-24 md:grid-cols-[1fr_1.25fr] md:items-center"><div><p className="text-xs font-bold uppercase text-primary">Friday, 18 September 2026</p><h2 className="mt-3 font-display text-4xl font-semibold sm:text-5xl">Today’s Office</h2><p className="mt-4 text-muted-foreground">[Liturgical season or feast placeholder]</p></div><div className="border-y border-border py-8"><p className="font-display text-2xl italic leading-9">“[Daily Office invitation placeholder]”</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild><Link to="/office/$book/$office/$date" params={{book:"1928",office:"morning",date:"2026-09-18"}}>Morning Prayer</Link></Button><Button variant="outline" asChild><Link to="/office/$book/$office/$date" params={{book:"1928",office:"evening",date:"2026-09-18"}}>Evening Prayer</Link></Button></div></div></section>
  <section className="border-y border-border bg-secondary/25"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24"><h2 className="font-display text-4xl font-semibold">Featured reading</h2><div className="mt-10 grid gap-10 md:grid-cols-3">{articles.slice(0,3).map(a => <ArticleCard article={a} key={a.slug}/>)}</div></div></section>
  <section className="mx-auto max-w-3xl px-5 py-16 text-center sm:px-8 sm:py-24"><Ornament/><h2 className="font-display text-4xl font-semibold">A short weekly letter on the Anglican way.</h2><p className="mx-auto mt-4 max-w-xl text-muted-foreground">[Email newsletter description placeholder]</p><form className="mx-auto mt-8 grid max-w-lg gap-3 sm:grid-cols-[1fr_auto]" onSubmit={e=>e.preventDefault()}><Input type="email" required placeholder="you@example.com" aria-label="Email address"/><Button type="submit">Subscribe</Button></form><p className="mt-3 text-xs text-muted-foreground">UI prototype only. No information is submitted.</p></section>
</main>; }
