/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FindAParishRouteImport } from './routes/find-a-parish'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as FindAParishParishIdRouteImport } from './routes/find-a-parish.$parishId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as PathsPathIdRouteImport } from './routes/paths.$pathId'
import { Route as OfficeBookOfficeDateRouteImport } from './routes/office.$book.$office.$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAParishRoute = FindAParishRouteImport.update({
  id: '/find-a-parish',
  path: '/find-a-parish',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAParishParishIdRoute = FindAParishParishIdRouteImport.update({
  id: '/$parishId',
  path: '/$parishId',
  getParentRoute: () => FindAParishRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const PathsPathIdRoute = PathsPathIdRouteImport.update({
  id: '/$pathId',
  path: '/$pathId',
  getParentRoute: () => PathsRoute,
} as any)
const OfficeBookOfficeDateRoute = OfficeBookOfficeDateRouteImport.update({
  id: '/$book/$office/$date',
  path: '/$book/$office/$date',
  getParentRoute: () => OfficeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/find-a-parish': typeof FindAParishRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/office': typeof OfficeRouteWithChildren
  '/paths': typeof PathsRouteWithChildren
  '/find-a-parish/$parishId': typeof FindAParishParishIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/learn/': typeof LearnIndexRoute
  '/office/$book/$office/$date': typeof OfficeBookOfficeDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/find-a-parish': typeof FindAParishRouteWithChildren
  '/office': typeof OfficeRouteWithChildren
  '/paths': typeof PathsRouteWithChildren
  '/find-a-parish/$parishId': typeof FindAParishParishIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/learn': typeof LearnIndexRoute
  '/office/$book/$office/$date': typeof OfficeBookOfficeDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/find-a-parish': typeof FindAParishRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/office': typeof OfficeRouteWithChildren
  '/paths': typeof PathsRouteWithChildren
  '/find-a-parish/$parishId': typeof FindAParishParishIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/learn/': typeof LearnIndexRoute
  '/office/$book/$office/$date': typeof OfficeBookOfficeDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/find-a-parish'
    | '/learn'
    | '/office'
    | '/paths'
    | '/find-a-parish/$parishId'
    | '/learn/$slug'
    | '/paths/$pathId'
    | '/learn/'
    | '/office/$book/$office/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/find-a-parish'
    | '/office'
    | '/paths'
    | '/find-a-parish/$parishId'
    | '/learn/$slug'
    | '/paths/$pathId'
    | '/learn'
    | '/office/$book/$office/$date'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/find-a-parish'
    | '/learn'
    | '/office'
    | '/paths'
    | '/find-a-parish/$parishId'
    | '/learn/$slug'
    | '/paths/$pathId'
    | '/learn/'
    | '/office/$book/$office/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FindAParishRoute: typeof FindAParishRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  OfficeRoute: typeof OfficeRouteWithChildren
  PathsRoute: typeof PathsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-parish': {
      id: '/find-a-parish'
      path: '/find-a-parish'
      fullPath: '/find-a-parish'
      preLoaderRoute: typeof FindAParishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-parish/$parishId': {
      id: '/find-a-parish/$parishId'
      path: '/$parishId'
      fullPath: '/find-a-parish/$parishId'
      preLoaderRoute: typeof FindAParishParishIdRouteImport
      parentRoute: typeof FindAParishRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/paths/$pathId': {
      id: '/paths/$pathId'
      path: '/$pathId'
      fullPath: '/paths/$pathId'
      preLoaderRoute: typeof PathsPathIdRouteImport
      parentRoute: typeof PathsRoute
    }
    '/office/$book/$office/$date': {
      id: '/office/$book/$office/$date'
      path: '/$book/$office/$date'
      fullPath: '/office/$book/$office/$date'
      preLoaderRoute: typeof OfficeBookOfficeDateRouteImport
      parentRoute: typeof OfficeRoute
    }
  }
}

interface FindAParishRouteChildren {
  FindAParishParishIdRoute: typeof FindAParishParishIdRoute
}

const FindAParishRouteChildren: FindAParishRouteChildren = {
  FindAParishParishIdRoute: FindAParishParishIdRoute,
}

const FindAParishRouteWithChildren = FindAParishRoute._addFileChildren(
  FindAParishRouteChildren,
)

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface OfficeRouteChildren {
  OfficeBookOfficeDateRoute: typeof OfficeBookOfficeDateRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeBookOfficeDateRoute: OfficeBookOfficeDateRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

interface PathsRouteChildren {
  PathsPathIdRoute: typeof PathsPathIdRoute
}

const PathsRouteChildren: PathsRouteChildren = {
  PathsPathIdRoute: PathsPathIdRoute,
}

const PathsRouteWithChildren = PathsRoute._addFileChildren(PathsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FindAParishRoute: FindAParishRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  OfficeRoute: OfficeRouteWithChildren,
  PathsRoute: PathsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
